Code improvements. Add router. Add context. Improve NoteForm handlers…
olhakhomyak/note-app pull request #1
Opened 2022-01-31 09:20 UTC by olhakhomyak

Application refactoring:

1. Added `react-router-dom`. Application has routes: ‘/create’, ‘/edit/:id’, ‘/preview/:id’;
2. 'Create' and 'Edit' components use the same functionality 'NoteForm.js';
3. ‘NoteForm.js’ contains validation for ‘title’ and ‘content’ fields. It’s done in `handleOnSubmit()` function before submitting the form. In case the form is not valid the Error block is displayed below the form, the ‘content’ field is highlighted in red color, the note is not saved;
4. Created context `NotesContext.js`, that wraps all components; nested components have access to `notes` array and `setNotes` function.

2022-01-31 15:38 UTC, OlegKotsubko approved these changes

2022-01-31 15:38 UTC, OlegKotsubko commented on src/components/NoteForm.js
> +                            error={content.length > CHARACTERS_LIMIT}
Если требование к валидации полей будет увеличиваться, то будет сложно дописывать методы. Могу рекомендовать вынести эту логику в отдельные метод(функцию) Сам сейчас думаю как это реализовать у себя в проекте

2022-01-31 17:26 UTC, Rastopyr requested changes

2022-01-31 17:26 UTC, Rastopyr commented on src/components/NoteForm.js
> +        <React.Fragment>
nit: можно использовать короткую нотацию `<>` вместо `<React.Fragment>`

2022-01-31 17:26 UTC, Rastopyr commented on src/components/Main.js
> +          <NotesContext.Provider
Provider стоит сделать отдельным компонентом. Посмотри плз примеры из последней демки.

Сейчас провайдер и его стейт определен внутри компонента Main.js и будет не очень удобно менять имплементацию контекста. К тому же это нарушение Single Responsibility Principle.

2022-01-31 17:26 UTC, Rastopyr commented on src/components/Main.js
> +            value={{ notes, setNotes }}
Давай попробуем описать тип значения и его заимлпементировать. Тип предлагаю сделать более сфокусированным(`updateNote`, `createNote`, `selectedNote`)

2022-02-02 13:06 UTC, Rastopyr commented on src/components/NoteForm.js
> +    const handleOnSubmit = (event) => {
Я бы еще предложил разгрузить логику этой функции. Тут очень много всего.

Будет нужна помощь - пингуй)

2022-02-02 22:52 UTC, Rastopyr requested changes

2022-02-02 22:52 UTC, Rastopyr commented on src/components/NoteForm.js
> +    const hasErrors = () => {
Тут используется общая логика для валидации. Я бы предложил упростить и сделать два флана `isTitleValid`/`isContentValid` и считать их не через метод, а через `useMemo` хук, о которому показывать ошибку

2022-02-02 22:52 UTC, Rastopyr commented on src/components/NoteForm.js
> +        if(error) return setErrorMsg(error);
Можно сделать стейт `showErrors`, и по нему отображать ошибки. А саму валидацию считать через useMemo как я предлагал выше

2022-02-02 22:52 UTC, Rastopyr commented on src/context/NotesContext.js
> +    dispatch,
Тут все еще определен очень общий API, посмотри пожалуйста демку со второго вебинара. Там есть пример  такого API для контекста.

Польза такого API заключается в том что, оно намного лучше отражает его назначение, и его проще использовать. В случае с dispatch нужно конкретно знать, что в него передавать, что сложно без знания конкретной имплементации.

2022-02-08 22:02 UTC, Rastopyr requested changes
Основное замечание по ПР. В некоторых компонентах ты провела разделение на View и интеграционный слой, а некоторые компоненты так и остались одним большим компонентом. Предлагаю закончить эту работу.

Так же есть пара небольших комментов по имплементации, они не должны занять много времени)

2022-02-08 22:02 UTC, Rastopyr commented on src/context/NotesContext.js
> +    localStorage.setItem("notes", JSON.stringify(notes));
Работу с получением или сохранением данных лучше спрятать за интерфейсом. Сейчас NotesProvider очень сильно зависит от localstorage и если изменится источник данных(graphql, https, websocket) то менять это логику будет возможно не очень удобно.

Пускай будут две функции, одна которая читает данные, другая пишет данные. И вместо прямой ссылки на использование localStorage, использовать эти функции.

2022-02-08 22:02 UTC, Rastopyr commented on src/context/NotesContext.js
> +const initialNotes = localStorage.notes ? JSON.parse(localStorage.notes) : []
Чтение лучше поместить в NotesProvider  и сделать lazy. `useReducer(..., () => getNotes())`.

Причин несколько
- При инициализации этого модуля затратится дополнительное время на чтение и парсинг
- В целом чтение и запись могут быть доступны по каким то условиям, которые на этапе инициализации модуля например не могут быть доступны. Например авторизован ли пользователь, находится ли приложение в offline режиме и тд

2022-02-08 22:02 UTC, Rastopyr commented on src/components/NoteForm.js
> +        if(err) return setErrorMsg(err)
Тут судя по логике могут отображаться только или ошибка для тайтла или ошибка для контента. Давай попробуем сделать так, чтобы при сабмите отображались все ошибки для всех полей.

2022-02-10 19:17 UTC, Rastopyr requested changes

2022-02-10 19:17 UTC, Rastopyr commented on src/context/NotesContext.js
> +  console.log(initialNotes, 777)
Забыла убрать console.log)

2022-02-10 19:17 UTC, Rastopyr commented on src/components/NoteForm.js
> +                            color={content.length > CHARACTERS_LIMIT ? "error" : "text.secondary"}
Тут внутри атрибута еще осталась какое то выражение которе дублирует правила валидации. Если правила изменятся, то придется менять в двух местах, и про то что логика дублируется можно легко забыть. Лучше использовать уже ранее посчитанный флаг

2022-02-10 19:17 UTC, Rastopyr commented on src/components/NoteForm.js
> +            setErrorMsg({...errorMsg, title: null});
Я не совсем понимаю как эта логика работает. Если есть ошибка в поле title то она сбрасывается?

2022-11-08 09:27 UTC, merged